from loguru import logger
import sys

logger.add(sys.stdout, level="TRACE")


class ScroogeCoin:
    serialNumber        = None      # The serial number inside a transaction. Probably autogenerated?
    value               = 0.0       # the number of ScroogeCoins this is worth
    recipient           = None      # public key of the recipient
    uuid                = None      # CoinID - combination of transaction ID and the coin's serial number within that transaction
    message             = None      # What actually happens in the transaction.
    signature           = None      # message, signed with the private key of the owner
    
    def __init__(self, serialNumber=serialNumber, value=value, recipient=recipient, message=message, signature=signature):
        self.serialNumber = serialNumber
        self.value = value
        self.recipient = recipient
        self.message = message
        self.signature = signature
        logger.info("Initializing coins worth {} and assigning to user {}".format(self.value, self.recipient.name))

    def __str__(self):
        return "\
            SerialNumber    : {} \n\
            Value           : {} \n\
            uuid            : {} \n\
            ".format(self.serialNumber, self.value, self.uuid)